/**
 * The Landing screen (F7-AC-16 – F7-AC-20, F7-UP-02, F7-UP-04).
 *
 * **The only screen reachable without an account, and the only one without the
 * app header.** One card, two tabs: *What he does* by default — sales rather
 * than function, five one-line claims, no feature list, no pricing, no scroll —
 * and *Log in*.
 *
 * **There is no sign-up path here, and its absence is the security model**
 * (F7-AC-01, F7-AC-18). Nobody can create an account; the owner creates them at
 * the provider. So: no register link, no password field, no forgotten-password
 * line — and nothing on this screen may be added later that implies otherwise.
 *
 * **Nothing distinguishes an authorised address from an unauthorised one**
 * (F7-AC-05, F7-UP-01). The server guarantees it; this screen must not undo the
 * guarantee by saying something different, which is why both paths reach the
 * same next step and the same words.
 */

import { type FormEvent, useEffect, useState } from 'react'
import { ApiError, requestCode, verifyCode } from '../../api'
import avatar from '../../assets/gaffer-avatar.png'
import shotOverview from '../../assets/shot-overview.png'
import shotPitch from '../../assets/shot-pitch.png'
import shotThinking from '../../assets/shot-thinking.png'
import shotTransfer from '../../assets/shot-transfer.png'
import styles from './Landing.module.css'

/**
 * `F7-AC-08`: the control carries a visible cooldown once used. Long enough to
 * match the server's own one-code-per-minute limit, so the screen never offers
 * a send that would be silently swallowed.
 */
const COOLDOWN_SECONDS = 60

/**
 * Where the last send is remembered, so the countdown survives a logout.
 *
 * **It did not, and that broke the promise directly above.** The countdown lived
 * in this component's state, so signing out and coming back wiped it while the
 * server went on counting — and the screen offered a send it had been built
 * specifically not to offer. Stephen hit it on 2026-09-16 on the first realistic
 * path anyone would take: ask for a code, log in, log out, ask again, nothing
 * arrives and nothing says why.
 *
 * **It leaks nothing.** The value is written by this browser's own action and
 * says only *you asked recently* — never whether any address has access, so
 * F7-AC-02 and F7-AC-07 are untouched. It is deliberately not keyed to the
 * address: erring towards a cooldown that is occasionally too cautious is the
 * right direction for a control whose whole job is to not offer a dead button.
 */
const LAST_SEND_KEY = 'gaffer.lastCodeRequest'

/** Seconds still to wait, from whatever this browser last recorded. 0 on anything unreadable. */
function cooldownRemaining(): number {
  try {
    const at = Number(localStorage.getItem(LAST_SEND_KEY))
    if (!Number.isFinite(at) || at <= 0) return 0
    return Math.max(0, Math.ceil((at + COOLDOWN_SECONDS * 1000 - Date.now()) / 1000))
  } catch {
    // Private windows and blocked site data both throw here. A cooldown is a
    // courtesy; losing it must never stop the screen rendering.
    return 0
  }
}

function recordSend(): void {
  try {
    localStorage.setItem(LAST_SEND_KEY, String(Date.now()))
  } catch {
    /* As above. The server is the limit; this is only the screen being honest. */
  }
}

/**
 * The claims, and the screen each one is about (F7-AC-16).
 *
 * **The copy is the handoff's**, with two departures, both because **F5 is below
 * the cut line**: the chip claim is gone entirely, and "and chips" is cut from
 * the second. Selling a chip planner that does not exist, on the only screen a
 * stranger sees, is not a design decision.
 *
 * **That leaves four, where the criterion says five.** Ruled 2026-09-15; the
 * divergence is in `docs/coverage-gaps.md` rather than hidden, and the fifth
 * comes back with F5.
 *
 * **The images are real screenshots of real screens**, regenerated by
 * `tests/e2e/shots.spec.ts`. A drawn mock-up of a product screen drifts from the
 * product silently.
 */
const CLAIMS: { src: string; cap: string; title: string; body: string }[] = [
  {
    src: shotPitch,
    cap: 'YOUR SQUAD',
    title: 'Up to date at all times',
    body: 'Availability, form, fixtures and projected points for every player.',
  },
  {
    src: shotOverview,
    cap: 'YOUR WEEK',
    title: 'Every call in one screen',
    body: 'Transfers, substitutions and armbands. All with confidence and impact.',
  },
  {
    src: shotTransfer,
    cap: 'HEAD TO HEAD',
    title: 'Swipe right to agree',
    body: 'Incoming against outgoing on every measure that matters.',
  },
  {
    src: shotThinking,
    cap: 'REFRESH',
    title: 'Update on demand',
    body: "Already made some changes and want the Gaffer's advice? No problem.",
  },
]

/** How long each claim holds before the next one. */
const ROTATE_MS = 4500

/** No scroll on this screen (F7-AC-16), so the column is measured, not stacked. */

type Tab = 'about' | 'login'

export function Landing({ onSignedIn, startOn = 'about' }: { onSignedIn: () => void; startOn?: Tab }) {
  const [tab, setTab] = useState<Tab>(startOn)
  const [open, setOpen] = useState(0)
  /** Set once the manager picks one himself — rotating past his choice is rude. */
  const [held, setHeld] = useState(false)

  const [email, setEmail] = useState('')
  const [code, setCode] = useState('')
  const [sent, setSent] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)
  const [cooldown, setCooldown] = useState(cooldownRemaining)

  useEffect(() => {
    if (cooldown <= 0) return
    const timer = setTimeout(() => setCooldown((c) => c - 1), 1000)
    return () => clearTimeout(timer)
  }, [cooldown])

  // It moves through the claims on its own (F7-AC-16: sales, no scroll, nothing
  // to work out). Stops for good the moment he takes hold of it.
  useEffect(() => {
    if (tab !== 'about' || held) return
    const timer = setTimeout(() => setOpen((i) => (i + 1) % CLAIMS.length), ROTATE_MS)
    return () => clearTimeout(timer)
  }, [tab, held, open])

  async function send(event: FormEvent) {
    event.preventDefault()
    // Belt as well as braces: the button is disabled, and a stray submit (Enter
    // in the field) must not spend a request the server will refuse anyway.
    if (cooldown > 0) return
    setError(null)
    setBusy(true)
    try {
      await requestCode(email.trim())
      // Always the same next step: an address with no access reaches here too,
      // and must not be able to tell (F7-AC-02, F7-AC-05).
      setSent(true)
      recordSend()
      setCooldown(COOLDOWN_SECONDS)
    } catch {
      setError('Could not reach the app. Try again in a moment.')
    } finally {
      setBusy(false)
    }
  }

  async function resend() {
    if (cooldown > 0) return
    setError(null)
    try {
      await requestCode(email.trim())
    } catch {
      /* Same silence as above: a failure here must not describe the address. */
    }
    recordSend()
    setCooldown(COOLDOWN_SECONDS)
  }

  async function logIn(event: FormEvent) {
    event.preventDefault()
    setError(null)
    setBusy(true)
    try {
      await verifyCode(email.trim(), code.trim())
      onSignedIn()
    } catch (cause) {
      /**
       * **Wrong, expired and already used read alike. Spent does not.**
       *
       * The first three are indistinguishable on purpose — the server knows
       * which it was and deliberately does not say. Exhaustion is the one case
       * F7-UP-02 asks to be called out: *"after five failures the code is spent,
       * and the inline error says so rather than leaving the manager retyping a
       * code that can no longer work."*
       *
       * Until slice 10 this line said the opposite, and carried a comment
       * asserting that was correct. It was a misreading of the criterion, and
       * the cost was real: five wrong guesses and the screen still invited a
       * sixth that could never succeed.
       *
       * Inline in the red card either way, never a toast (F7-AC-20).
       */
      setError(
        cause instanceof ApiError && cause.code === 'code_spent'
          ? 'That code is used up — five attempts is the limit. Request another and try again.'
          : 'That code did not work. It may have expired or already been used. Request another and try again.',
      )
    } finally {
      setBusy(false)
    }
  }

  return (
    <main className={styles.screen}>
      <div className={styles.head}>
        <img className={styles.avatar} src={avatar} alt="" />
        <h1 className={styles.wordmark}>The Gaffer</h1>
        <p className={styles.role}>Your Fantasy Premier League Assistant Manager</p>
        <p className={styles.promise}>Advice across every gameweek, every decision.</p>
        {/* Stated up front, so a visitor learns before typing anything that an
            unrecognised address gets them nowhere (F7-AC-17). */}
        <span className={styles.badge} data-testid="invite-only">
          <i className={styles.badgeDot} aria-hidden="true" />
          INVITE ONLY · NO PUBLIC SIGN-UP
        </span>
      </div>

      <section className={styles.card}>
        <nav className={styles.tabs} role="tablist">
          <button
            role="tab"
            aria-selected={tab === 'about'}
            className={tab === 'about' ? styles.tabOn : styles.tab}
            onClick={() => setTab('about')}
            type="button"
          >
            What he does
          </button>
          <button
            role="tab"
            aria-selected={tab === 'login'}
            className={tab === 'login' ? styles.tabOn : styles.tab}
            onClick={() => setTab('login')}
            data-testid="tab-login"
            type="button"
          >
            Log in
          </button>
        </nav>

        {tab === 'about' ? (
          /* Device on the left, the claims beside it — the open one carries its
             sentence and the rest stay one line each, which is what lets the
             whole screen fit without scrolling (F7-AC-16). */
          <div className={styles.about} data-testid="about">
            <div className={styles.shot} aria-hidden="true">
              {CLAIMS.map((c, index) => (
                <img
                  key={c.cap}
                  className={index === open ? styles.shotOn : styles.shotOff}
                  src={c.src}
                  alt=""
                />
              ))}
            </div>

            <ul className={styles.claims}>
              {CLAIMS.map((c, index) => (
                <li key={c.cap}>
                  <button
                    className={index === open ? styles.claimOn : styles.claim}
                    aria-expanded={index === open}
                    onClick={() => {
                      setHeld(true)
                      setOpen(index)
                    }}
                    type="button"
                  >
                    <span className={styles.claimCap}>{c.cap}</span>
                    <span className={styles.claimTitle}>{c.title}</span>
                    {index === open ? <span className={styles.claimBody}>{c.body}</span> : null}
                  </button>
                </li>
              ))}
            </ul>
          </div>
        ) : (
          <div className={styles.login}>
            {/* Inline, in a red card inside the login card — never a transient
                toast (F7-AC-20, F7-UP-02). */}
            {error ? (
              <div className={styles.error} role="alert" data-testid="login-error">
                <span className={styles.errorDisc} aria-hidden="true">
                  !
                </span>
                <span>{error}</span>
              </div>
            ) : null}

            {!sent ? (
              <form onSubmit={send} className={styles.form}>
                <label className={styles.label} htmlFor="email">
                  Email
                </label>
                <input
                  id="email"
                  className={styles.field}
                  type="email"
                  inputMode="email"
                  autoComplete="email"
                  autoCapitalize="none"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="you@example.com"
                />
                {/* **This button ignored the cooldown until 2026-09-16**, and
                    that is the whole of the defect Stephen found. The countdown
                    was only ever applied to *Send another code*, which lives on
                    the next step — so signing out and returning put him back
                    here, in front of a button that looked ready and did nothing.
                    A send the server will swallow must not be offered on either
                    step (F7-AC-08). */}
                <button
                  className={styles.button}
                  type="submit"
                  disabled={busy || email.trim() === '' || cooldown > 0}
                  data-testid="send-code"
                >
                  {busy
                    ? 'Sending…'
                    : cooldown > 0
                      ? `Send another code in ${String(cooldown)}s`
                      : 'Send me a code'}
                </button>
              </form>
            ) : (
              <form onSubmit={logIn} className={styles.form}>
                <div className={styles.sentTo}>Code sent to {email}</div>
                <label className={styles.label} htmlFor="code">
                  Six-digit code
                </label>
                <input
                  id="code"
                  className={`${styles.field} ${styles.codeField}`}
                  inputMode="numeric"
                  autoComplete="one-time-code"
                  value={code}
                  onChange={(e) => setCode(e.target.value)}
                  placeholder="123456"
                />
                <button className={styles.button} type="submit" disabled={busy || code.trim() === ''}>
                  {busy ? 'Checking…' : 'Log in'}
                </button>

                {/* F7-AC-08: the cooldown is visible, so a tap that would do
                    nothing is never offered as one that would. */}
                <button
                  className={styles.quiet}
                  type="button"
                  onClick={() => void resend()}
                  disabled={cooldown > 0}
                  data-testid="send-another"
                >
                  {cooldown > 0 ? `Send another code in ${String(cooldown)}s` : 'Send another code'}
                </button>

                <button
                  className={styles.quiet}
                  type="button"
                  onClick={() => {
                    setSent(false)
                    setCode('')
                    setError(null)
                  }}
                >
                  Use a different address
                </button>
              </form>
            )}
          </div>
        )}
      </section>

      {/* The standing disclaimer (F7-AC-19), with the attribution the licence
          requires beside it (STE-53). */}
      <footer className={styles.disclaimer}>
        <p>
          Not affiliated with the Premier League or Fantasy Premier League. Advice only — you make
          every move yourself in the FPL app.
        </p>
        <p>
          Projections by{' '}
          <a href="https://fantasyfootballiq.app" target="_blank" rel="noreferrer">
            Fantasy Football IQ
          </a>
          .
        </p>
      </footer>
    </main>
  )
}
